const API_ROOT_PATH = "/api";
const DATA_API_PATH = "/data";
const USERS_API_PATH = "/users";
const INFO_API_PATH = "/info";

// USERS
const DELETE_USER = `${API_ROOT_PATH}${USERS_API_PATH}/deleteUser`;
const LIST_USERS_API = `${API_ROOT_PATH}${USERS_API_PATH}/listUsers`;
const UPDATE_USER_STATUS = `${API_ROOT_PATH}${USERS_API_PATH}/changeStatus`;

// DATA
const SUBMIT_DATA_API = `${API_ROOT_PATH}${DATA_API_PATH}/submit_data`;
const EXPORT_DATA_API = `${API_ROOT_PATH}${DATA_API_PATH}/export_data`;

// DEADLINES
const SET_DEADLINE_API = `${API_ROOT_PATH}${INFO_API_PATH}/setDeadline`;
const GET_DEADLINE_API = `${API_ROOT_PATH}${INFO_API_PATH}/getDeadline`;
const DEL_DEADLINE_API = `${API_ROOT_PATH}${INFO_API_PATH}/delDeadline`;

module.exports = {
  SUBMIT_DATA_API,
  EXPORT_DATA_API,
  LIST_USERS_API,
  UPDATE_USER_STATUS,
  DELETE_USER,
  SET_DEADLINE_API,
  GET_DEADLINE_API,
  DEL_DEADLINE_API,
};
